
## Configuration options, can be used for all designs
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

create_clock -period 10.000 -name CLK -waveform {0.000 5.000} -add [get_ports CLK]

set_property PACKAGE_PIN D9 [get_ports CLK]
set_property PACKAGE_PIN AA19 [get_ports RSTN]


set_property PACKAGE_PIN AB26 [get_ports {RSW[3]}]
set_property PACKAGE_PIN AB25 [get_ports {RSW[2]}]
set_property PACKAGE_PIN AB24 [get_ports {RSW[1]}]
set_property PACKAGE_PIN AB22 [get_ports {RSW[0]}]


set_property PACKAGE_PIN AC22 [get_ports {PSW[2]}]
set_property PACKAGE_PIN AC23 [get_ports {PSW[1]}]
set_property PACKAGE_PIN AC24 [get_ports {PSW[0]}]


set_property PACKAGE_PIN U21 [get_ports {LED_OUT[7]}]
set_property PACKAGE_PIN R21 [get_ports {LED_OUT[6]}]
set_property PACKAGE_PIN Y21 [get_ports {LED_OUT[5]}]
set_property PACKAGE_PIN R22 [get_ports {LED_OUT[4]}]
set_property PACKAGE_PIN W21 [get_ports {LED_OUT[3]}]
set_property PACKAGE_PIN T22 [get_ports {LED_OUT[2]}]
set_property PACKAGE_PIN T23 [get_ports {LED_OUT[1]}]
set_property PACKAGE_PIN T24 [get_ports {LED_OUT[0]}]


set_property PACKAGE_PIN P21 [get_ports {SEG_7A[7]}]
set_property PACKAGE_PIN P20 [get_ports {SEG_7A[6]}]
set_property PACKAGE_PIN M21 [get_ports {SEG_7A[5]}]
set_property PACKAGE_PIN L20 [get_ports {SEG_7A[4]}]
set_property PACKAGE_PIN K21 [get_ports {SEG_7A[3]}]
set_property PACKAGE_PIN J21 [get_ports {SEG_7A[2]}]
set_property PACKAGE_PIN H21 [get_ports {SEG_7A[1]}]
set_property PACKAGE_PIN G21 [get_ports {SEG_7A[0]}]

set_property PACKAGE_PIN F18 [get_ports {SEG_7B[7]}]
set_property PACKAGE_PIN E18 [get_ports {SEG_7B[6]}]
set_property PACKAGE_PIN F19 [get_ports {SEG_7B[5]}]
set_property PACKAGE_PIN F20 [get_ports {SEG_7B[4]}]
set_property PACKAGE_PIN E20 [get_ports {SEG_7B[3]}]
set_property PACKAGE_PIN E21 [get_ports {SEG_7B[2]}]
set_property PACKAGE_PIN E22 [get_ports {SEG_7B[1]}]
set_property PACKAGE_PIN E23 [get_ports {SEG_7B[0]}]

set_property PACKAGE_PIN D18 [get_ports {SEG_7C[7]}]
set_property PACKAGE_PIN D19 [get_ports {SEG_7C[6]}]
set_property PACKAGE_PIN D20 [get_ports {SEG_7C[5]}]
set_property PACKAGE_PIN D21 [get_ports {SEG_7C[4]}]
set_property PACKAGE_PIN D23 [get_ports {SEG_7C[3]}]
set_property PACKAGE_PIN D24 [get_ports {SEG_7C[2]}]
set_property PACKAGE_PIN D25 [get_ports {SEG_7C[1]}]
set_property PACKAGE_PIN D26 [get_ports {SEG_7C[0]}]

set_property PACKAGE_PIN C17 [get_ports {SEG_7D[7]}]
set_property PACKAGE_PIN C18 [get_ports {SEG_7D[6]}]
set_property PACKAGE_PIN C19 [get_ports {SEG_7D[5]}]
set_property PACKAGE_PIN C21 [get_ports {SEG_7D[4]}]
set_property PACKAGE_PIN C22 [get_ports {SEG_7D[3]}]
set_property PACKAGE_PIN C23 [get_ports {SEG_7D[2]}]
set_property PACKAGE_PIN C24 [get_ports {SEG_7D[1]}]
set_property PACKAGE_PIN C26 [get_ports {SEG_7D[0]}]

set_property PACKAGE_PIN B17 [get_ports {SEG_7E[7]}]
set_property PACKAGE_PIN B19 [get_ports {SEG_7E[6]}]
set_property PACKAGE_PIN B20 [get_ports {SEG_7E[5]}]
set_property PACKAGE_PIN B21 [get_ports {SEG_7E[4]}]
set_property PACKAGE_PIN B22 [get_ports {SEG_7E[3]}]
set_property PACKAGE_PIN B24 [get_ports {SEG_7E[2]}]
set_property PACKAGE_PIN B25 [get_ports {SEG_7E[1]}]
set_property PACKAGE_PIN B26 [get_ports {SEG_7E[0]}]

set_property PACKAGE_PIN A17 [get_ports {SEG_7F[7]}]
set_property PACKAGE_PIN A18 [get_ports {SEG_7F[6]}]
set_property PACKAGE_PIN A19 [get_ports {SEG_7F[5]}]
set_property PACKAGE_PIN A20 [get_ports {SEG_7F[4]}]
set_property PACKAGE_PIN A22 [get_ports {SEG_7F[3]}]
set_property PACKAGE_PIN A23 [get_ports {SEG_7F[2]}]
set_property PACKAGE_PIN A24 [get_ports {SEG_7F[1]}]
set_property PACKAGE_PIN A25 [get_ports {SEG_7F[0]}]

set_property PACKAGE_PIN L22 [get_ports {SEG_7G[7]}]
set_property PACKAGE_PIN K22 [get_ports {SEG_7G[6]}]
set_property PACKAGE_PIN H22 [get_ports {SEG_7G[5]}]
set_property PACKAGE_PIN G22 [get_ports {SEG_7G[4]}]
set_property PACKAGE_PIN F24 [get_ports {SEG_7G[3]}]
set_property PACKAGE_PIN F23 [get_ports {SEG_7G[2]}]
set_property PACKAGE_PIN F22 [get_ports {SEG_7G[1]}]
set_property PACKAGE_PIN E25 [get_ports {SEG_7G[0]}]

set_property PACKAGE_PIN N22 [get_ports {SEG_7H[7]}]
set_property PACKAGE_PIN M22 [get_ports {SEG_7H[6]}]
set_property PACKAGE_PIN L23 [get_ports {SEG_7H[5]}]
set_property PACKAGE_PIN K23 [get_ports {SEG_7H[4]}]
set_property PACKAGE_PIN J24 [get_ports {SEG_7H[3]}]
set_property PACKAGE_PIN J23 [get_ports {SEG_7H[2]}]
set_property PACKAGE_PIN H23 [get_ports {SEG_7H[1]}]
set_property PACKAGE_PIN G24 [get_ports {SEG_7H[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RSTN]


set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_OUT[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {PSW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PSW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PSW[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {RSW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RSW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RSW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RSW[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7C[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7E[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7F[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_7H[0]}]


